#%RAML 1.0 Library
uses:
  strings: stringTypes.raml
  pragma: pragma.raml

types:
  SecretSpec:
    type: object
    discriminator: exposure
    properties:
      exposure:
        type: string
        description: |
          The type of exposure for the given secret.
          `file` designates a secret that will be rendered into an environment variable.
          `env` designates a secret that will be rendered into an environment variable.
        enum: [ file, env ]
      source:
        type: string
        description: The source referenced in the secrets store.
  SecretFile:
    type: object
    description: |
      Optional config for the file that shall be exposed. If not specified, a default file path will be composed
      based on the given source.
    properties:
      path:
        type: string
        description: Fully qualified path to the file.
  FileBasedSecretSpec:
    type: SecretSpec
    discriminatorValue: file
    properties:
      file?: SecretFile
  SecretEnvVar:
    type: object
    description: |
      Optional config for the environment variable that shall be exposed. If not specified, a default environment
      variable name will be composed based on the given source.
    properties:
      name:
        type: string
        description: The name of the env var to be exposed.
  EnvVarSecretSpec:
    type: SecretSpec
    discriminatorValue: env
    properties:
      exposure:
        type: string
        enum: [ env ]
      env?: SecretEnvVar